### ISSUE TITLE
Add install.sh to conveniently add mercari wrench during CircleCI

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [cloudspannerecosystem/wrench#55]
## WHAT
It would be great if we can add an `install.sh` script like in [golangcli-lint](https://golangci-lint.run/usage/install/#other-ci)

Exampe of Install.sh -> https://github.com/reviewdog/reviewdog/blob/master/install.sh

### Example 
``` yaml
jobs:
  lint:
    working_directory: ~/reviewdog
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run:
          name: System information
          command: 'echo "Golang $(go version)"'
      - run: 'curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $(go env GOPATH)/bin'
      - run:
          command: |-
            set +o pipefail
            golint ./... | reviewdog -f=golint -name=golint-circleci -reporter=github-pr-review

```

## WHY
It would make it easy to install mercari-wrench for Ci
